

#ifndef APPLICATION_H
#define APPLICATION_H

// Also see the following files generated by SMT32CubeMX : 
//   include/stm32f4xx_hal_conf.h

/**
 * @name Application GPIO Configuration
 */
/**@{*/   
    #define APP_ENABLE_GPIO            1
/**@}*/ 


/**
 * @name Application Systick and Time Configuration
 */
/**@{*/   
    #define APP_ENABLE_SYSTICK         1
    #define APP_USE_CORE_SYSTICK       1
    #define APP_ENABLE_CRON            1
/**@}*/ 

/**
 * @name Application Device ID Configuration
 */
/**@{*/   
    #define APP_ENABLE_ID       1
    #define APP_ID_TRIMFUNC     1
/**@}*/ 

/**
 * @name Application EEPROM Configuration
 */
/**@{*/   
    #define APP_ENABLE_EEPROM         0
    #define APP_EEPROM_PROVIDER       2
    #define APP_EEPROM_SIZE           1024
    #define APP_EEPROM_SIZETYPE       uint16_t
/**@}*/ 

/**
 * @name Application Entropy Configuration
 */
/**@{*/   
    #define APP_ENABLE_RAND                 1
    #define APP_ENABLE_ENTROPY              APP_ENABLE_RAND
    #define APP_ENTROPY_POOL_SIZE           16
    #define APP_ENTROPY_MODE                2
/**@}*/ 

/**
 * @name Application USB Configuration
 */
/**@{*/    
    #define APP_ENABLE_USB_HOST             0   // Not implemented.
    #define APP_ENABLE_USB_DEVICE           1
    #define APP_ENABLE_USB                  (APP_ENABLE_USB_DEVICE | APP_ENABLE_USB_HOST)
    #define APP_USB_DEVICE_RHPORT           0
    #define APP_USB_DESCR_VID               1155
    #define APP_USB_DESCR_PID               22336
    #define APP_USB_DESCR_VERSION           0x0100
    #define APP_USB_DESCR_MANUFACTURER      "EBS Development"
    #define APP_USB_DESCR_PRODUCT           "STM32F4 Development Sandbox"
    #define APP_USB_DESCR_IF_CDC            "TinyUSB CDC"
    #define APP_USB_POWER                   400
    #define APP_USBCDC_IFACES               1
    #define APP_USBCDC_IFACE                0
    #define APP_BLINK_FOR_USB_STATUS        1
/**@}*/ 

#endif